# NumPy – Numerical Python
## 1. Why Learn NumPy?

#### What is it?

NumPy is a powerful Python library for numerical computations. It provides fast and memory-efficient multi-dimensional arrays.

#### Why we need it?

1.Pure Python lists are slow for large datasets.

2.NumPy arrays are optimized for speed and vectorized operations.

3.Most Data Science & Machine Learning libraries (like Pandas, Scikit-Learn, TensorFlow) are built on top of NumPy.

#### Where is it used?

1.Data Analysis

2.Machine Learning & Deep Learning

3.Image Processing (OpenCV, PIL use NumPy arrays)

5.Scientific Computing & Simulations


## 2. Importing NumPy





In [4]:
import numpy as np



## 3. Arrays vs Python Lists


In [5]:
import numpy as np
import time



# Python list


In [6]:
py_list = [i for i in range(1000000)]



# NumPy array


In [7]:
np_array = np.arange(1000000)



# Time comparison


In [ ]:
start = time.time()
sum(py_list)
print("Python list sum time:", time.time() - start)

start = time.time()
np.sum(np_array)
print("NumPy array sum time:", time.time() - start)

Python list sum time: 0.005510807037353516
NumPy array sum time: 0.0010008811950683594


## 4. Creating Arrays
1.np.arange(start, stop, step)

Purpose: Creates an array of numbers starting from start up to but not including stop, incremented by step.

Your code: np.arange(0, 10, 2)

Start = 0

Stop = 10 (exclusive)

Step = 2

2.np.linspace(start, stop, num)

Purpose: Creates an array of num equally spaced numbers between start and stop (inclusive).

Your code: np.linspace(0, 1, 5)

Start = 0

Stop = 1 (inclusive)

5 numbers evenly spaced

In [11]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [12]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

# From list 


In [13]:
arr = np.array([1, 2, 3, 4, 5])
print("Array:", arr)


Array: [1 2 3 4 5]



# Zeros and Ones


In [18]:
print("Zeros:", np.zeros((2,3)))
print("Ones:", np.ones((2,3)))


Zeros: [[0. 0. 0.]
 [0. 0. 0.]]
Ones: [[1. 1. 1.]
 [1. 1. 1.]]



# Range and Linspace


In [20]:
print("Arange:", np.arange(0, 10, 2))
print("Linspace:", np.linspace(0, 1, 11))

Arange: [0 2 4 6 8]
Linspace: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


## 5. Array Properties


In [21]:

arr = np.array([[1,2,3],[4,5,6]])
print("Array shape:", arr.shape)
print("Array dtype:", arr.dtype)
print("Array size:", arr.size)
print("Array ndim:", arr.ndim)

Array shape: (2, 3)
Array dtype: int32
Array size: 6
Array ndim: 2


## 6. Indexing and Slicing

In [22]:

arr = np.array([10,20,30,40,50])
print("Element at index 2:", arr[2])
print("Elements from index 1 to 3:", arr[1:4])
print("Elements at indices 0, 2, 4:", arr[[0,2,4]])
print("Every second element:", arr[::2])
print("Reversed array:", arr[::-1])


Element at index 2: 30
Elements from index 1 to 3: [20 30 40]
Elements at indices 0, 2, 4: [10 30 50]
Every second element: [10 30 50]
Reversed array: [50 40 30 20 10]


In [23]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Matrix:\n", matrix)
print("Matrix shape:", matrix.shape)
print("Matrix dtype:", matrix.dtype)
print("Matrix size:", matrix.size)
print("Matrix ndim:", matrix.ndim)
print(matrix[0,1]) # element at row 0, col 1
print(matrix[1,:]) # entire row 1
print(matrix[:,2]) # entire col 2


Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix shape: (3, 3)
Matrix dtype: int32
Matrix size: 9
Matrix ndim: 2
2
[4 5 6]
[3 6 9]


# Matrix operations


In [24]:
print("Transpose:\n", matrix.T)
print("Sum of all elements:", np.sum(matrix))
print("Sum of each column:", np.sum(matrix, axis=0))
print("Sum of each row:", np.sum(matrix, axis=1))
print("Mean of all elements:", np.mean(matrix))
print("Mean of each column:", np.mean(matrix, axis=0))
print("Mean of each row:", np.mean(matrix, axis=1))
print("Element-wise multiplication:\n", matrix * 2)
print("Matrix multiplication:\n", np.dot(matrix, matrix))  

Transpose:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
Sum of all elements: 45
Sum of each column: [12 15 18]
Sum of each row: [ 6 15 24]
Mean of all elements: 5.0
Mean of each column: [4. 5. 6.]
Mean of each row: [2. 5. 8.]
Element-wise multiplication:
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
Matrix multiplication:
 [[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
